baseURL: "https://beargrllys.github.io/"
title: Multitab's Portfolio
languageCode: en-us
title: Multitab's Portfolio
theme : PaperMod

params:
  assets:
      disableFingerprinting: true
  title: Multitab's Portfolio
  description: "멀티탭의 개발 포트폴리오 정리용 블로그입니다."
  keywords: [Blog, Portfolio, PaperMod]
  author: Multitab
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  homeInfoParams:
    enabled: true
    Title: "안녕하세요! \U0001F44B"
    Content: 멀티탭의 개발 아카이브에 오신걸 환영합니다.

  socialIcons:
    - name: github
      url: "https://github.com/beargrllys"
    - name: linkedin
      url: "https://www.linkedin.com/in/%EC%A7%80%EC%83%81-%EC%9C%A4-52b375155/"
    - name: instagram
      url: "https://www.instagram.com/js774433/"

menu:
  main:
    - identifier: Profile
      name: Profile
      url: /posts/profiles
      weight: 10
    - identifier: Projects
      name: Projects
      url: /tags/project/
      weight: 20
    - identifier: Company
      name: Company
      url: /tags/company/
      weight: 30
    - identifier: Price
      name: Price
      url: /tags/price/
      weight: 40
    - identifier: Social
      name: Social
      url: /tags/social/
      weight: 50
    - identifier: Class
      name: Class
      url: /tags/class/
      weight: 60
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 70
    - identifier: contact
      name: Contacts
      url: /contact/contacts/
      weight: 80

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary